
stages:
  - lint
  - alpine
  - centos
  - nvidia
  - scratch
  - ubuntu
  - vaapi




recent-update-run:
  image: python:3
  stage: lint
  script:
    - ./update.py
    - git status
    - git diff-index --quiet HEAD
  artifacts:
    expire_in: 1 days
    paths:
    - docker-images/


linter-black:
  image: python:3
  stage: lint
  before_script:
    - pip install black
  script:
    - black .

.docker:
  image: docker:latest
  variables:
    GIT_STRATEGY: none
    SHORT_IMAGE: "ffmpeg:${SHORT_VERSION}-${VARIANT}"
    IMAGE: "ffmpeg:${VERSION}-${VARIANT}"
  services:
    - docker:19-dind
  script:
    - docker build -t "${IMAGE}" -t "${SHORT_IMAGE}" --build-arg MAKEFLAGS="-j$(($(nproc) + 1))" docker-images/${VERSION}/${VARIANT}
  after_script:
    - docker run --rm ${IMAGE} -buildconf
    - echo "Built ${IMAGE}"


include:
  - local: 'docker-images/gitlab-ci.yml'
